### ISSUE TITLE
update package.json file with scripts

### ISSUE THREAD

**Issue by chinwobble** [elmish/templates#65]
It would be useful to update the package json file with scripts to run perform all the common actions like and run.

it could look like this:
```javascript
{
"scripts" : {
    "start": "webpack-dev-server",
    "build": "webpack"
  }
}
```

The package.json file was the first project I checked when I installed the template to test out elmish react but it didn't contain anything.

**Comment by MangelMaxime** [comment]
Hello @chinwobble , 

the instructions to run the templates can be found in the [`README.md`](https://github.com/elmish/templates/blob/master/src/react/Content/README.md#building-and-running-the-app) file.

In general, I expect the user to check the `README.md` file first when using a template because it's can explain a lot more things that jumping into the code :)

**Comment by MangelMaxime** [comment]
It seems we added script to package.json since this issue was open
